openapi: '3.0.3'
info:
  title: Open_Xrd
  version: '1.0'
servers:
  # - url: https://api.server.test/v1
  - url: http://127.0.0.1:8000
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
